[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
  base = "frontend"
  command = "npm run build" # Change to your React build command
  publish = "frontend/build" # This tells Netlify to serve only frontend
